apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: standalone
  name: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: standalone
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: standalone
    spec:
      containers:
      - args:
        - bin/pulsar
        - standalone
        env:
        - name: PULSAR_MEM
          value: ' -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g'
        image: apachepulsar/pulsar:2.8.1
        imagePullPolicy: ""
        name: standalone
        ports:
        - containerPort: 8080
        - containerPort: 6650
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
